site_name: Awesome Neural Network Reprogrammability
site_description: A curated list of resources on neural network reprogrammability
site_url: https://username.github.io/awesome-reprogrammability

theme:
  name: readthedocs
  palette:
    - scheme: default
      primary: blue
      accent: blue
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Home: index.md
  - Papers: sections/papers.md
  - Taxonomy: sections/taxonomy.md
  - Evaluations: sections/evaluations.md
  - Leaderboards: sections/leaderboards.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
